export const SPRINT_GOAL_SHARE_LABELS = {
  sprintObjective: "Objetivo del sprint",
  generalObjective: "Objetivo general",
  storiesInGoal: "Historias en el objetivo",
  stateObjective: "Estados objetivo",
  tagObjective: "Tags objetivo",
  userStoryColumn: "Historia de usuario",
  originalStateColumn: "Estado original",
  originalTagsColumn: "Tags iniciales",
  targetStateColumn: "Estado objetivo",
  targetTagsColumn: "Tags objetivo",
  currentStateColumn: "Estado actual",
  currentTagsColumn: "Tags actual",
  generatedOn: "Generado el",
  overflowStories: "historia",
  overflowStoriesPlural: "historias",
  overflowSuffix: "adicional",
  overflowSuffixPlural: "adicionales",
} as const;
