"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { Download, Loader2 } from "lucide-react";

import { CopilotErrorAlert } from "@/components/copilot/copilot-error-alert";
import { Button } from "@/components/ui/button";
import { ReportsTimeLogAlerts } from "@/components/reports/time-log/reports-time-log-alerts";
import { ReportsTimeLogEmptyState } from "@/components/reports/time-log/reports-time-log-empty-state";
import { ReportsTimeLogFilters } from "@/components/reports/time-log/reports-time-log-filters";
import { ReportsTimeLogStaleBanner } from "@/components/reports/time-log/reports-time-log-stale-banner";
import {
  ReportsTimeLogTable,
  ReportsTimeLogTableSkeleton,
} from "@/components/reports/time-log/reports-time-log-table";
import { useHoursReport } from "@/hooks/reports/use-hours-report";
import type { AdoCatalogSnapshot } from "@/lib/ado/types";
import { appToast } from "@/lib/toast";
import type {
  HoursReportExcelQuerySchema,
  HoursReportPeriodSchema,
  HoursReportRequestSchema,
} from "@/lib/schemas/reports-hours";

export type ReportsTimeLogContentProps = {
  catalog: AdoCatalogSnapshot;
  initialScopes: { projectIds: string[]; teamIds: string[] };
  adoExecutionReady: boolean;
};

function defaultPeriod(): HoursReportPeriodSchema {
  const now = new Date();
  const y = now.getUTCFullYear();
  const m = String(now.getUTCMonth() + 1).padStart(2, "0");
  return { kind: "month", monthKey: `${y}-${m}` };
}

/** Fecha actual en formato `YYYY-MM-DD` (UTC). */
function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}

function defaultMonthKey(): string {
  const p = defaultPeriod();
  return p.kind === "month" ? p.monthKey : "";
}

function resolveExcelQuery(
  period: HoursReportPeriodSchema,
  projectIds: string[],
  teamIds: string[],
): HoursReportExcelQuerySchema {
  return {
    periodKind: period.kind,
    monthKey: period.kind === "month" ? period.monthKey : undefined,
    fromIso: period.kind === "range" ? period.fromIso : undefined,
    toIso: period.kind === "range" ? period.toIso : undefined,
    projectIds,
    teamIds,
  };
}

export function ReportsTimeLogContent({
  catalog,
  initialScopes,
  adoExecutionReady,
}: Readonly<ReportsTimeLogContentProps>) {
  const [period, setPeriod] = useState<HoursReportPeriodSchema>(defaultPeriod());
  const [rangeFrom, setRangeFrom] = useState<string>(todayIso());
  const [rangeTo, setRangeTo] = useState<string>(todayIso());
  const [projectIds, setProjectIds] = useState<string[]>(initialScopes.projectIds);
  const [teamIds, setTeamIds] = useState<string[]>(initialScopes.teamIds);
  const [downloadingExcel, setDownloadingExcel] = useState(false);

  const hoursReport = useHoursReport();
  const autoGeneratedRef = useRef(false);

  // Sin selección explícita el reporte cubre todo el catálogo, de modo que
  // siempre viajen proyectos/equipos concretos y el servidor pueda cargar el
  // roster de cada equipo (las personas que deben salir en la tabla).
  const allProjectNames = useMemo(
    () => catalog.projects.map((p) => p.name),
    [catalog.projects],
  );
  const allTeamNames = useMemo(
    () => catalog.teams.map((t) => t.name),
    [catalog.teams],
  );

  const buildPayload = useCallback(
    (nextPeriod: HoursReportPeriodSchema): HoursReportRequestSchema => ({
      period: nextPeriod,
      scopes: {
        projectIds: projectIds.length > 0 ? projectIds : allProjectNames,
        teamIds: teamIds.length > 0 ? teamIds : allTeamNames,
      },
    }),
    [projectIds, teamIds, allProjectNames, allTeamNames],
  );

  const payload = useMemo(
    () => buildPayload(period),
    [buildPayload, period],
  );

  const onGenerate = useCallback(async () => {
    await hoursReport.generate(payload);
  }, [hoursReport, payload]);

  const markStaleNow = useCallback(
    (nextPeriod: HoursReportPeriodSchema) => {
      hoursReport.markStale(buildPayload(nextPeriod));
    },
    [hoursReport, buildPayload],
  );

  useEffect(() => {
    if (autoGeneratedRef.current) return;
    if (!adoExecutionReady) return;
    autoGeneratedRef.current = true;
    void hoursReport.generate(payload);
  }, [hoursReport, payload, adoExecutionReady]);

  const year = period.kind === "month" ? Number(period.monthKey.slice(0, 4)) : new Date().getUTCFullYear();
  const monthKey = period.kind === "month" ? period.monthKey : `${year}-01`;

  const switchToMonth = useCallback(() => {
    const next: HoursReportPeriodSchema = { kind: "month", monthKey: defaultMonthKey() };
    setPeriod(next);
    markStaleNow(next);
  }, [markStaleNow]);

  const switchToRange = useCallback(() => {
    const next: HoursReportPeriodSchema = { kind: "range", fromIso: rangeFrom, toIso: rangeTo };
    setPeriod(next);
    markStaleNow(next);
  }, [rangeFrom, rangeTo, markStaleNow]);

  const onYearChange = useCallback(
    (y: number) => {
      if (period.kind !== "month") return;
      const next: HoursReportPeriodSchema = {
        kind: "month",
        monthKey: `${y}-${period.monthKey.slice(5, 7)}`,
      };
      setPeriod(next);
      markStaleNow(next);
    },
    [period, markStaleNow],
  );

  const onMonthKeyChange = useCallback(
    (k: string) => {
      const next: HoursReportPeriodSchema = { kind: "month", monthKey: k };
      setPeriod(next);
      markStaleNow(next);
    },
    [markStaleNow],
  );

  const onRangeFromChange = useCallback(
    (iso: string) => {
      setRangeFrom(iso);
      const next: HoursReportPeriodSchema =
        period.kind === "range" ? { kind: "range", fromIso: iso, toIso: period.toIso } : period;
      setPeriod(next);
      markStaleNow(next);
    },
    [period, markStaleNow],
  );

  const onRangeToChange = useCallback(
    (iso: string) => {
      setRangeTo(iso);
      const next: HoursReportPeriodSchema =
        period.kind === "range" ? { kind: "range", fromIso: period.fromIso, toIso: iso } : period;
      setPeriod(next);
      markStaleNow(next);
    },
    [period, markStaleNow],
  );

  const onProjectIdsChange = useCallback(
    (ids: string[]) => {
      setProjectIds(ids);
      markStaleNow(period);
    },
    [markStaleNow, period],
  );

  const onTeamIdsChange = useCallback(
    (ids: string[]) => {
      setTeamIds(ids);
      markStaleNow(period);
    },
    [markStaleNow, period],
  );

  const onExportExcel = useCallback(async () => {
    if (hoursReport.status === "stale") {
      appToast.warning("El reporte está desactualizado. Regenera antes de exportar.");
      return;
    }
    if (!hoursReport.result || hoursReport.result.rows.length === 0) {
      appToast.warning("No hay datos para exportar.");
      return;
    }
    setDownloadingExcel(true);
    try {
      // Mismos scopes efectivos que la generación (vacío ⇒ todo el catálogo),
      // para que el Excel refleje exactamente la tabla.
      const query = resolveExcelQuery(
        period,
        payload.scopes.projectIds,
        payload.scopes.teamIds,
      );
      await hoursReport.downloadExcel(query);
    } finally {
      setDownloadingExcel(false);
    }
  }, [hoursReport, period, payload]);

  const showStale = hoursReport.status === "stale";
  const showError = hoursReport.status === "error" || Boolean(hoursReport.errorMessage);
  const hasGenerated = hoursReport.status === "ready" || hoursReport.status === "stale";
  const showEmpty =
    hasGenerated &&
    hoursReport.result !== null &&
    hoursReport.result.rows.length === 0;
  const showExport = hasGenerated && (hoursReport.result?.rows.length ?? 0) > 0;

  return (
    <div className="flex flex-col gap-6">
      <ReportsTimeLogFilters
        projects={catalog.projects}
        teams={catalog.teams}
        period={period}
        year={year}
        monthKey={monthKey}
        rangeFrom={rangeFrom}
        rangeTo={rangeTo}
        selectedProjectIds={projectIds}
        selectedTeamIds={teamIds}
        onPeriodChange={(kind) => (kind === "month" ? switchToMonth() : switchToRange())}
        onYearChange={onYearChange}
        onMonthKeyChange={onMonthKeyChange}
        onRangeFromChange={onRangeFromChange}
        onRangeToChange={onRangeToChange}
        onProjectIdsChange={onProjectIdsChange}
        onTeamIdsChange={onTeamIdsChange}
        onGenerate={onGenerate}
        generating={hoursReport.status === "generating"}
        payload={payload}
        exportButton={
          showExport ? (
            <Button onClick={() => void onExportExcel()} disabled={downloadingExcel}>
              {downloadingExcel ? (
                <>
                  <Loader2 className="size-4 animate-spin" aria-hidden />
                  Descargando...
                </>
              ) : (
                <>
                  <Download className="size-4" aria-hidden />
                  Exportar Excel
                </>
              )}
            </Button>
          ) : null
        }
      />

      {showStale ? (
        <ReportsTimeLogStaleBanner onRegenerate={onGenerate} regenerating={hoursReport.status === "generating"} />
      ) : null}

      {showError ? <CopilotErrorAlert message={hoursReport.errorMessage ?? "Error desconocido"} /> : null}

      {hoursReport.result !== null ? (
        <ReportsTimeLogAlerts alerts={hoursReport.result.alerts} />
      ) : null}

      {hoursReport.status === "generating" ? (
        <ReportsTimeLogTableSkeleton />
      ) : (
        <>
          {showEmpty ? <ReportsTimeLogEmptyState /> : null}
          <ReportsTimeLogTable rows={hoursReport.result?.rows ?? []} />
        </>
      )}
    </div>
  );
}