"use client";

import { useCallback, useEffect, useRef } from "react";

import { Download, Loader2 } from "lucide-react";

import { CopilotErrorAlert } from "@/components/copilot/copilot-error-alert";
import { Button } from "@/components/ui/button";
import { ReportsTimeLogAlerts } from "@/components/reports/time-log/reports-time-log-alerts";
import { ReportsTimeLogEmptyState } from "@/components/reports/time-log/reports-time-log-empty-state";
import { ReportsTimeLogFilters } from "@/components/reports/time-log/reports-time-log-filters";
import { ReportsTimeLogNewsNotConfiguredAlert } from "@/components/reports/time-log/reports-time-log-news-not-configured-alert";
import { ReportsTimeLogStaleBanner } from "@/components/reports/time-log/reports-time-log-stale-banner";
import {
  ReportsTimeLogTable,
  ReportsTimeLogTableSkeleton,
} from "@/components/reports/time-log/reports-time-log-table";
import { AssigneeVisibilityCombobox } from "@/components/sprints/stats/assignee-visibility-combobox";
import { useExportHoursReportToExcel } from "@/hooks/reports/use-export-hours-report-to-excel";
import { useHoursReport } from "@/hooks/reports/use-hours-report";
import { useHoursReportFilters } from "@/hooks/reports/use-hours-report-filters";
import { useHoursReportView } from "@/hooks/reports/use-hours-report-view";
import type { AdoCatalogSnapshot } from "@/lib/ado/types";
import { NEWS_NOT_CONFIGURED_CODE } from "@/lib/reports/hours/errors";
import { useAssigneeVisibilityStore } from "@/store/assignee-visibility-store";

function ReportsTimeLogErrorAlert({
  errorCode,
  errorMessage,
}: Readonly<{ errorCode: string | null; errorMessage: string }>) {
  if (errorCode === NEWS_NOT_CONFIGURED_CODE) {
    return <ReportsTimeLogNewsNotConfiguredAlert message={errorMessage} />;
  }
  return <CopilotErrorAlert message={errorMessage} />;
}

export type ReportsTimeLogContentProps = {
  catalog: AdoCatalogSnapshot;
  initialScopes: { projectIds: string[]; teamIds: string[] };
  adoExecutionReady: boolean;
};

export function ReportsTimeLogContent({
  catalog,
  initialScopes,
  adoExecutionReady,
}: Readonly<ReportsTimeLogContentProps>) {
  const hoursReport = useHoursReport();
  const autoGeneratedRef = useRef(false);

  const filters = useHoursReportFilters({
    catalog,
    initialScopes,
    hoursReport,
  });

  const hiddenPersons = useAssigneeVisibilityStore((s) => s.hidden);
  const togglePersonVisibility = useAssigneeVisibilityStore((s) => s.toggle);

  const view = useHoursReportView({
    hoursReport,
    hiddenPersons,
    nameFilter: filters.nameFilter,
  });

  const { exportExcel, downloadingExcel } = useExportHoursReportToExcel({
    hoursReport,
    payload: filters.payload,
    allPersons: view.allPersons,
    hiddenPersons,
  });

  const onGenerate = useCallback(async () => {
    await hoursReport.generate(filters.payload);
  }, [hoursReport, filters.payload]);

  // Auto-genera el reporte en cuanto el backend declara que puede ejecutar.
  useEffect(() => {
    if (autoGeneratedRef.current) return;
    if (!adoExecutionReady) return;
    autoGeneratedRef.current = true;
    void hoursReport.generate(filters.payload);
  }, [hoursReport, filters.payload, adoExecutionReady]);

  return (
    <div className="flex flex-col gap-6">
      <ReportsTimeLogFilters
        projects={catalog.projects}
        teams={filters.teams}
        period={filters.period}
        year={filters.year}
        monthKey={filters.monthKey}
        rangeFrom={filters.rangeFrom}
        rangeTo={filters.rangeTo}
        selectedProjectIds={filters.projectIds}
        selectedTeamIds={filters.teamIds}
        nameFilter={filters.nameFilter}
        isStale={hoursReport.status === "stale"}
        onPeriodChange={filters.onPeriodChange}
        onYearChange={filters.onYearChange}
        onMonthKeyChange={filters.onMonthKeyChange}
        onRangeFromChange={filters.onRangeFromChange}
        onRangeToChange={filters.onRangeToChange}
        onProjectIdsChange={filters.onProjectIdsChange}
        onTeamIdsChange={filters.onTeamIdsChange}
        onNameFilterChange={filters.onNameFilterChange}
        onGenerate={onGenerate}
        generating={hoursReport.status === "generating"}
        payload={filters.payload}
        visibilityControl={
          view.allPersons.length > 0 ? (
            <AssigneeVisibilityCombobox
              assignees={view.allPersons}
              hiddenAssignees={hiddenPersons}
              onToggle={togglePersonVisibility}
              disabled={hoursReport.status === "generating"}
            />
          ) : null
        }
        exportButton={
          view.showExport ? (
            <Button
              variant="default"
              onClick={() => void exportExcel()}
              disabled={downloadingExcel}
            >
              {downloadingExcel ? (
                <>
                  <Loader2 className="size-4 animate-spin" aria-hidden />
                  Descargando...
                </>
              ) : (
                <>
                  <Download className="size-4" aria-hidden />
                  Exportar Excel
                </>
              )}
            </Button>
          ) : null
        }
      />

      {view.showStale ? <ReportsTimeLogStaleBanner /> : null}

      {view.showError ? (
        <ReportsTimeLogErrorAlert
          errorCode={hoursReport.errorCode}
          errorMessage={hoursReport.errorMessage ?? "Error desconocido"}
        />
      ) : null}

      {hoursReport.result !== null ? (
        <ReportsTimeLogAlerts alerts={hoursReport.result.alerts} />
      ) : null}

      {hoursReport.status === "generating" ? (
        <ReportsTimeLogTableSkeleton />
      ) : (
        <>
          {view.showEmpty ? <ReportsTimeLogEmptyState /> : null}
          <ReportsTimeLogTable rows={view.filteredRows} />
        </>
      )}
    </div>
  );
}