import type { PullRequestListItem } from "@/lib/pull-requests/types";

export const MOCK_PULL_REQUESTS: readonly PullRequestListItem[] = [
  {
    id: 1842,
    title: "Implementar nuevo catálogo de filtros y facetado",
    status: "needs_review",
    approvalSummary: null,
    sourceBranch: "feature/catalog-filters",
    targetBranch: "develop",
    author: "Luis Martínez",
    commentCount: 12,
    changedFileCount: 24,
    updatedAt: "2026-09-11T14:20:00.000Z",
    isMine: false,
    needsMyReview: true,
    isPending: false,
    repository: "STUDIA-LMS-WEB",
    project: "STUDIA",
  },
  {
    id: 1840,
    title: "Refactorizar servicios de autenticación v2",
    status: "approved",
    approvalSummary: "Aprobado (2/2)",
    sourceBranch: "feature/auth-v2",
    targetBranch: "develop",
    author: "Luis Martínez",
    commentCount: 4,
    changedFileCount: 11,
    updatedAt: "2026-09-11T11:05:00.000Z",
    isMine: true,
    needsMyReview: false,
    isPending: false,
    repository: "STUDIA-CORE",
    project: "STUDIA",
  },
  {
    id: 1838,
    title: "Migración de entornos a staging",
    status: "changes_requested",
    approvalSummary: null,
    sourceBranch: "hotfix/env",
    targetBranch: "staging",
    author: "Sofía Castro",
    commentCount: 8,
    changedFileCount: 6,
    updatedAt: "2026-09-10T18:40:00.000Z",
    isMine: false,
    needsMyReview: true,
    isPending: false,
    repository: "STUDIA-API",
    project: "STUDIA",
  },
  {
    id: 1835,
    title: "Optimización de bundle y tree-shaking",
    status: "waiting",
    approvalSummary: null,
    sourceBranch: "feature/perf-opt",
    targetBranch: "main",
    author: "Carlos Vega",
    commentCount: 1,
    changedFileCount: 9,
    updatedAt: "2026-09-10T09:15:00.000Z",
    isMine: false,
    needsMyReview: false,
    isPending: true,
    repository: "STUDIA-LMS-WEB",
    project: "STUDIA",
  },
  {
    id: 1831,
    title: "Actualizar dependencias de seguridad",
    status: "draft",
    approvalSummary: null,
    sourceBranch: "chore/cve-patches",
    targetBranch: "main",
    author: "Bot Renovate",
    commentCount: 0,
    changedFileCount: 3,
    updatedAt: "2026-09-09T16:00:00.000Z",
    isMine: true,
    needsMyReview: false,
    isPending: true,
    repository: "STUDIA-CORE",
    project: "STUDIA",
  },
];

export const MOCK_FILTER_PROJECTS = ["STUDIA"] as const;
export const MOCK_FILTER_REPOSITORIES = [
  "STUDIA-LMS-WEB",
  "STUDIA-CORE",
  "STUDIA-API",
] as const;
